// Mock data for demo mode — realistic scenario for a mid-tier aesthetic clinic
import type { Insight } from '@/lib/insights/generator'

export const DEMO_RESPONSES: Record<string, string> = {
  // Perfil
  clinic_specialty: 'Medicina Estetica',
  clinic_years: '6',
  clinic_rooms: '2',
  clinic_patients_month: '85',
  clinic_city: 'Guadalajara',

  // Operaciones
  ops_scheduling: 'WhatsApp',
  ops_confirmation: 'Si manual',
  ops_cancellation_rate: '20-30%',
  ops_avg_consult_time: '50',
  ops_schedule_hours: 'Lunes a Viernes 9am-7pm, Sabado 9am-2pm',
  ops_reception_staff: 'Si, tiempo parcial',
  ops_bottleneck: 'No hay sistema de confirmacion automatica y muchas citas se pierden por olvido del paciente',

  // Finanzas
  fin_avg_ticket: '9500',
  fin_payment_methods: 'Efectivo,Tarjeta,Transferencia',
  fin_accounting: 'Hoja de calculo',
  fin_top_treatments: 'Botox, Rellenos, Hidroxiapatita de calcio',
  fin_fixed_costs: 'Aproximadamente',
  fin_revenue_goal: '800000',
  fin_growth_vs_last_year: 'Crecio entre 5-20%',

  // Equipo
  team_total: '4',
  team_has_nurse: 'Si',
  team_has_coordinator: 'No',
  team_has_marketing: 'No',
  team_training: 'On the job',
  team_main_challenge: 'El equipo no tiene protocolo claro para el seguimiento de pacientes despues de la consulta',

  // Journey
  journey_acquisition: 'Referidos,Instagram',
  journey_instagram: 'Si, pero poco activa',
  journey_return_rate: '40-60%',
  journey_followup: 'No',
  journey_upsell: 'A veces',
  journey_loyalty: 'No',
  journey_reviews: 'A veces',

  // Tecnologia
  tech_mgmt_software: 'Excel/Sheets',
  tech_ehr: 'No',
  tech_website: 'Si, desactualizado',
  tech_payment_system: 'Terminal bancaria',
  tech_biggest_gap: 'Software para gestionar expedientes y agenda de forma integrada',
}

export const DEMO_CLINIC = {
  id: 'demo-clinic-id',
  name: 'Clinica Estetica Dr. Vargas',
  doctor_name: 'Dr. Roberto Vargas',
  specialty: 'Medicina Estetica',
  city: 'Guadalajara',
  years_operating: 6,
  patients_per_month: 85,
  rooms: 2,
}

export const DEMO_INSIGHTS: (Insight & { id: string })[] = [
  {
    id: '1',
    title: 'Confirma automaticamente tus citas',
    description: 'Cada cita sin confirmar es un riesgo de ingreso. Con tu volumen actual de 85 pacientes al mes, una tasa de 25% de no-shows representa $201,875 MXN perdidos mensualmente.',
    action_steps: [
      'Configura una secuencia de WhatsApp con 3 mensajes: 48h antes (confirmacion con boton), 24h antes (recordatorio), 2h antes (recordatorio final)',
      'Designa a tu asistente como responsable de monitorear respuestas',
      'Para clinicas con > 50 citas/mes: considera Wati, Respond.io o Brevo para automatizar',
      'Mide el delta de cancelaciones en 30 dias',
    ],
    timeline: '1-3 dias para implementar',
    responsible: 'Asistente / Coordinador',
    category: 'Operaciones',
    impact: 'alto' as const,
    effort: 'bajo' as const,
    urgency_level: 1,
    revenue_mxn: 201875,
    priority_score: 6.75,
    is_highlighted: true,
  },
  {
    id: '2',
    title: 'Empieza a hacer seguimiento post-consulta',
    description: 'El 68% de los pacientes que no regresan no lo hacen porque se sintieron olvidados. Con 85 pacientes al mes, un protocolo basico puede recuperar hasta $161,500/mes.',
    action_steps: [
      'Crea una secuencia de 3 mensajes post-consulta: 48h despues, 2 semanas y 6 semanas',
      'Segmenta por tipo de tratamiento — el mensaje para botox no es el mismo que para rellenos',
      'Lleva un registro de quienes respondieron vs quienes no',
      'Meta: 30% de tasa de respuesta en los primeros 60 dias',
    ],
    timeline: '3-5 dias para armar los mensajes',
    responsible: 'Asistente / Doctor para revisar el tono',
    category: 'Journey del Paciente',
    impact: 'alto' as const,
    effort: 'bajo' as const,
    urgency_level: 1,
    revenue_mxn: 161500,
    priority_score: 6.75,
    is_highlighted: true,
  },
  {
    id: '3',
    title: 'Ofrece siempre el siguiente tratamiento en la misma consulta',
    description: 'Con 85 pacientes/mes, hay $96,900/mes en tratamientos complementarios que no se estan vendiendo porque no se ofrecen en el momento correcto.',
    action_steps: [
      "Crea un 'Menu de Siguiente Paso' por tratamiento: Botox → skinbooster; Relleno → plan de mantenimiento",
      "El doctor termina cada consulta con: 'Lo que sigue para ti seria...'",
      "La asistente cierra con: '¿Le agendamos esa cita hoy?'",
      'Registra tasa de conversion de upsell por semana',
    ],
    timeline: '1 dia (solo requiere crear el menu y ensayarlo)',
    responsible: 'Doctor + Asistente',
    category: 'Journey del Paciente',
    impact: 'alto' as const,
    effort: 'bajo' as const,
    urgency_level: 1,
    revenue_mxn: 96900,
    priority_score: 6.75,
    is_highlighted: true,
  },
  {
    id: '4',
    title: 'Tu clinica no tiene control financiero formal',
    description: 'Sin saber exactamente cuanto te cuesta operar, es imposible saber si tu clinica es rentable o simplemente factura bien.',
    action_steps: [
      'En los proximos 7 dias: lista todos tus costos fijos mensuales',
      'Semana 2: clasifica tratamientos por margen bruto real',
      'Mes 1: implementa Contpaq, Alegra o Google Sheet estructurado',
      'Mes 2-3: identifica los 3 tratamientos de mayor margen y priorizalos',
    ],
    timeline: '30-60 dias para control operativo basico',
    responsible: 'Doctor + Contador',
    category: 'Finanzas',
    impact: 'alto' as const,
    effort: 'medio' as const,
    urgency_level: 2,
    revenue_mxn: 0,
    priority_score: 2.25,
    is_highlighted: false,
  },
  {
    id: '5',
    title: 'No tienes coordinador de experiencia del paciente',
    description: 'Cuando el doctor hace tambien de coordinador, el costo de oportunidad es enorme: cada minuto en confirmaciones es un tratamiento que no se realizo.',
    action_steps: [
      'Define el perfil: habilidades de atencion al cliente, seguimiento y organizacion',
      'Responsabilidades: confirmacion, seguimiento post-consulta, coordinacion de agenda',
      'Si no hay presupuesto: reasigna estas tareas a tu recepcionista con protocolo escrito',
      'KPI del rol: tasa de retorno, tasa de reagendamiento, NPS basico',
    ],
    timeline: '30-45 dias',
    responsible: 'Doctor (decision) → Asistente actual (implementacion)',
    category: 'Equipo',
    impact: 'alto' as const,
    effort: 'medio' as const,
    urgency_level: 2,
    revenue_mxn: 0,
    priority_score: 2.25,
    is_highlighted: false,
  },
  {
    id: '6',
    title: 'Tu clinica opera sin sistema de gestion',
    description: 'El techo de crecimiento sin sistema esta tipicamente en los 60-80 pacientes/mes. Con 85 pacientes ya estas en la zona de riesgo.',
    action_steps: [
      'Evalua: Doctoralia (agenda + expediente + resenas), Medesk, Crecer Medical',
      'Criterios: integracion WhatsApp, expediente electronico, reportes de facturacion',
      'Implementa primero solo la agenda digital',
      'Capacita a tu equipo con el sistema ANTES de decirle a los pacientes',
    ],
    timeline: '60-90 dias',
    responsible: 'Doctor (decision) + Asistente (implementacion diaria)',
    category: 'Tecnologia',
    impact: 'alto' as const,
    effort: 'alto' as const,
    urgency_level: 3,
    revenue_mxn: 0,
    priority_score: 1.5,
    is_highlighted: false,
  },
]
